services:
  # SSH 跳板主機 (SSH Server - 圖中的 A 主機)
  ssh-gateway:
    build:
      context: .
      dockerfile: Dockerfile.ssh-server
    container_name: ssh-gateway
    hostname: ssh-gateway
    ports:
      - "2222:22"  # 對外開放 SSH 端口
    networks:
      - public-net
      - internal-net
    volumes:
      - ./ssh-keys:/home/sshuser/.ssh
    environment:
      - SSH_USER=sshuser
      - SSH_PASSWORD=password123
    restart: unless-stopped

  # 目標主機 1 (Target Server - 圖中的 B 主機)
  target-server-1:
    build:
      context: .
      dockerfile: Dockerfile.target-server
    container_name: target-server-1
    hostname: target-server-1
    ports:
      - "3389"  # 模擬 RDP 服務
      - "80"    # 模擬 Web 服務
    networks:
      - internal-net  # 只在內部網路，外部無法直接存取
    environment:
      - SERVER_NAME=target-server-1
      - WEB_PORT=80
    restart: unless-stopped

  # 目標主機 2 (Target Server - 圖中的 C 主機)
  target-server-2:
    build:
      context: .
      dockerfile: Dockerfile.target-server
    container_name: target-server-2
    hostname: target-server-2
    ports:
      - "3306"  # 模擬 MySQL 服務
      - "22"    # SSH 服務
    networks:
      - internal-net  # 只在內部網路
    environment:
      - SERVER_NAME=target-server-2
      - DB_PORT=3306
    restart: unless-stopped

networks:
  # 公共網路（模擬外部網路）
  public-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
  
  # 內部網路（模擬公司內網）
  internal-net:
    driver: bridge
    internal: true  # 限制外部存取
    ipam:
      config:
        - subnet: 10.100.0.0/24
